blevesearch/zapx

build_test.go, dict_test.go, go.mod, go.sum, merge_test.go, new.go
=> update New method to work directly with index.Document

build_test.go, dict_test.go, go.mod, go.sum, merge_test.go, new.go
=> v14 update New method to work directly with index.Document

build_test.go, dict_test.go, go.mod, go.sum, merge_test.go, new.go
=> v13 update New method to work directly with index.Document

build_test.go, dict_test.go, go.mod, go.sum, merge_test.go, new.go
=> v12 update New method to work directly with index.Document

build_test.go, dict_test.go, go.mod, go.sum, merge_test.go, new.go
=> v11 update New method to work directly with index.Document

build.go
-which helps to persist a memory segment into
the given writer.
=> Implement io.WriterTo interface

build.go, go.mod, go.sum
* e3f6785 Abhinav Dangeti | Upgrade to bleve_index_api@v1.0.1
* 83db2ee Sreekanth Sivasankaran | Implement io.WriterTo interface (#73)
=> v14 io.WriterTo interface & bleve_index_api upgrade

build.go, go.mod, go.sum
* 76d795e Abhinav Dangeti | Upgrade to bleve_index_api@v1.0.1
* 040fda7 Sreekanth Sivasankaran | Implement io.WriterTo interface (#73)
=> v13 io.WriterTo interface & bleve_index_api upgrade

build.go, go.mod, go.sum
* 8d1e062 Abhinav Dangeti | Upgrade to bleve_index_api@v1.0.1
* 24eee2a Sreekanth Sivasankaran | Implement io.WriterTo interface (#73)
=> v12 io.WriterTo interface & bleve_index_api upgrade

build.go, go.mod, go.sum
* c352a14 Abhinav Dangeti | Upgrade to bleve_index_api@v1.0.1
* 9031d6f Sreekanth Sivasankaran | Implement io.WriterTo interface (#73)
=> v11 io.WriterTo interface & bleve_index_api upgrade

contentcoder.go, intcoder.go, new.go
- Refactored the code with respect to disk stats computation, mainly the adding of chunks in content and int coders for location and doc values based information.
- Addressed a bug which was basically with respect to interim object maintaining state across New() calls.
=> Disk stats computation bug fix

posting.go, segment.go
This is a backward compatibility PR in references to changes in https://github.com/blevesearch/scorch_segment_api/pull/20
=> Update zap v14.x with DiskStatsReporter changes

doc_test.go, docvalues.go, go.mod, go.sum
=> v14.x backport changes for bytesRead per query changes

doc_test.go, docvalues.go, go.mod, go.sum
related to https://github.com/blevesearch/zapx/pull/142
=> v12.x backport changes for bytesRead per query changes

go.mod, go.sum
=> [v15] Upgrade to vellum@v1.0.10

go.mod, go.sum
=> [v14] Upgrade to vellum@v1.0.10

go.mod, go.sum
=> [v13] Upgrade to vellum@v1.0.10

go.mod, go.sum
=> [v12] Upgrade to vellum@v1.0.10

go.mod, go.sum
=> [v11] Upgrade to vellum@v1.0.10

go.mod, go.sum
To absorb:
* 0ea762e Abhi Dangeti | Temporarily revert free-ing C pointers/buffers - adding a TODO for this (#7)
=> Use latest of blevesearch/go-faiss

new.go, section_faiss_vector_index.go, section_inverted_text_index.go, segment.go
- includes fixes related to the io stats computation (bytesWritten and bytesRead) in light of new index sections PR.
=> fixing IO stats computation

section_faiss_vector_index.go
- fixes the vector index metadata tracking logic in the merge paths.
=> MB-60071: fixing out of bound slice access panic

go.mod, go.sum
* 9aa0040 Rahul Rampure | MB-60739: Fix slicing issue
=> MB-60739: Faiss UP

go.mod, go.sum
* f0dac5c Thejas-bhat | MB-60816: Using runtime.LockOSThread to bind the running goroutine to the specific OS thread.
=> MB-60816: Upgrade go-faiss for fix

section_faiss_vector_index.go
This PR adds a HNSW index as the coarse quantiser for IVF indexes - avoid brute force search for the centroids closest to the query vector and instead use a HNSW centroid index .
Verified this to not impact recall significantly in E2E testing - 
1. 10M dataset - 768 dims
Case | Recall | Accuracy
without change | 0.85795 | 0.897
with change | 0.8565999999999999 | 0.895
2. 5M dataset - 1536 dims
Case | Recall | Accuracy
without change | 0.9591	| 0.979
with change | 0.95811 | 0.981
=> MB-60943 - Add a coarse quantiser to the IVF indexes

go.mod, go.sum
Brings in:
* 7531ec8 Rahul Rampure | MB-62221: Fix platform specific behaviour
=> MB-62221: Upgrade go-faiss

go.mod, go.sum
Requires blevesearch/faiss@d9db66a
=> MB-62221: Upgrade go-faiss to v1.0.19      

go.mod, go.sum
* 1bb080b Abhi Dangeti | MB-61889: Address corner case with ivf_nprobe_pct
=> MB-61889: Upgrade go-faiss for corner case fix

merge.go, section_inverted_text_index.go
For https://github.com/blevesearch/bleve/issues/1662
=> Add nil pointer checks for postings before dereference

merge.go, new.go
Backports https://github.com/blevesearch/zapx/pull/271
=> [v15] Add nil pointer checks for postings before dereference

faiss_vector_posting.go
This PR adds minimises adding vector IDs to a bitmap, even in batches, for high selectivity cases.
It instead adds ineligible vector IDs to the bitmap.
=> MB-63992 - High selectivity specific optimisations.

go.mod, go.sum
For https://github.com/blevesearch/zapx/issues/285, possible situation on ARM
=> [v15] Upgrade github.com/golang/snappy version

go.mod, go.sum
* 2127bb0 Likith B | MB-64513: Removing modification of max codes based on filtered document size
=> MB-64513: Upgrade blevesearch/go-faiss for fix

.github/workflows/tests.yml, docvalues.go, faiss_vector_cache.go, faiss_vector_posting.go, faiss_vector_test.go, go.mod, merge.go, read.go, segment.go
Also, some other minor refactoring.
=> Remove unnecessary check while loading docVecIDmap from vector cache

faiss_vector_cache.go
Remove unnecessary assignments and cleanup.
=> Remove unnecessary function redirect within faiss_vector_cache.go
