go.mod, go.sum, plugin.go
=> remove plugin method

go.mod, go.sum, plugin.go
=> v14 remove plugin method

go.mod, go.sum, plugin.go
=> v13 remove plugin method

go.mod, go.sum, plugin.go
=> v12 remove plugin method

go.mod, go.sum, plugin.go
=> v11 remove plugin method

intDecoder.go, merge.go, posting.go
Even with custom or different chunk size/factors, it still
looks safe and efficient to copy the freq,norm,locs bytes
for saving the extra encodings of many uvarint's.
Chunk factor differences across postings per segment
doesn't look to affect the functionality here.
By restoring this optimization, the performance of the merge
paths improved by
wildcard - 30%
fuzzy2 - 34%
for showfast tests.
ref - https://issues.couchbase.com/browse/MB-41399
=>  Restore the mergeTermFreqNormLocsByCopying optimization (#44)

merge.go, new.go, posting.go
Enabling configurable freq/norm with storage
With freq/norm disabled at the index layer, storage
layer no longer needs to persist both freq/norm related
information onto disk.
A special frequency value of zero/0 is interpreted as
a configuration for skipping the processing of norm
value.
So with freq/norm disabled, zap always store the freq
value of 0 along with an LSB indicating the presence
of location data.
Savings are mostly of 1 byte per occurrence of the
token as we always persist a freq value of 0 with
the location LSB.
=> Enabling configurable freq/norm

posting.go
+ Related to: blevesearch/bleve#1606
=> PostingsIterator: Address nil pointer dereferencing

posting.go
+ Related to: https://github.com/blevesearch/bleve/issues/1606
=> [v11] PostingsIterator: Address nil pointer dereferencing

posting.go
+ Related to: https://github.com/blevesearch/bleve/issues/1606
=> [v12] PostingsIterator: Address nil pointer dereferencing

posting.go
+ Related to: https://github.com/blevesearch/bleve/issues/1606
=> [v13] PostingsIterator: Address nil pointer dereferencing

posting.go
+ Related to: https://github.com/blevesearch/bleve/issues/1606
=> [v14] PostingsIterator: Address nil pointer dereferencing

posting.go
Intend to address this panic ..
```
runtime.errorString: runtime error: invalid memory address or nil pointer dereference
File "github.com/blevesearch/zapx/v15@v15.3.1/posting.go", line 595, in (*PostingsIterator).nextDocNumAtOrAfter
File "github.com/blevesearch/zapx/v15@v15.3.1/posting.go", line 476, in (*PostingsIterator).nextAtOrAfter
File "github.com/blevesearch/zapx/v15@v15.3.1/posting.go", line 471, in (*PostingsIterator).Advance
File "github.com/blevesearch/bleve/v2@v2.2.1/index/scorch/snapshot_index_tfr.go", line 152, in (*IndexSnapshotTermFieldReader).Advance
File "github.com/blevesearch/bleve/v2@v2.2.1/search/searcher/search_term.go", line 105, in (*TermSearcher).Advance
...
```
.. highlighted here: https://github.com/blevesearch/bleve/issues/1606#issuecomment-993150219
=> Move all iterator forward until a match, only if possible

posting.go
Intend to address this panic ..
runtime.errorString: runtime error: invalid memory address or nil pointer dereference
File "github.com/blevesearch/zapx/v15@v15.3.1/posting.go", line 595, in (*PostingsIterator).nextDocNumAtOrAfter
File "github.com/blevesearch/zapx/v15@v15.3.1/posting.go", line 476, in (*PostingsIterator).nextAtOrAfter
File "github.com/blevesearch/zapx/v15@v15.3.1/posting.go", line 471, in (*PostingsIterator).Advance
File "github.com/blevesearch/bleve/v2@v2.2.1/index/scorch/snapshot_index_tfr.go", line 152, in (*IndexSnapshotTermFieldReader).Advance
File "github.com/blevesearch/bleve/v2@v2.2.1/search/searcher/search_term.go", line 105, in (*TermSearcher).Advance
...
.. highlighted here: https://github.com/blevesearch/bleve/issues/1606#issuecomment-993150219
=> [v11] Move all iterator forward until a match, only if possible

posting.go
Intend to address this panic ..
runtime.errorString: runtime error: invalid memory address or nil pointer dereference
File "github.com/blevesearch/zapx/v15@v15.3.1/posting.go", line 595, in (*PostingsIterator).nextDocNumAtOrAfter
File "github.com/blevesearch/zapx/v15@v15.3.1/posting.go", line 476, in (*PostingsIterator).nextAtOrAfter
File "github.com/blevesearch/zapx/v15@v15.3.1/posting.go", line 471, in (*PostingsIterator).Advance
File "github.com/blevesearch/bleve/v2@v2.2.1/index/scorch/snapshot_index_tfr.go", line 152, in (*IndexSnapshotTermFieldReader).Advance
File "github.com/blevesearch/bleve/v2@v2.2.1/search/searcher/search_term.go", line 105, in (*TermSearcher).Advance
...
.. highlighted here: https://github.com/blevesearch/bleve/issues/1606#issuecomment-993150219
=> [v13] Move all iterator forward until a match, only if possible

posting.go
Intend to address this panic ..
runtime.errorString: runtime error: invalid memory address or nil pointer dereference
File "github.com/blevesearch/zapx/v15@v15.3.1/posting.go", line 595, in (*PostingsIterator).nextDocNumAtOrAfter
File "github.com/blevesearch/zapx/v15@v15.3.1/posting.go", line 476, in (*PostingsIterator).nextAtOrAfter
File "github.com/blevesearch/zapx/v15@v15.3.1/posting.go", line 471, in (*PostingsIterator).Advance
File "github.com/blevesearch/bleve/v2@v2.2.1/index/scorch/snapshot_index_tfr.go", line 152, in (*IndexSnapshotTermFieldReader).Advance
File "github.com/blevesearch/bleve/v2@v2.2.1/search/searcher/search_term.go", line 105, in (*TermSearcher).Advance
...
.. highlighted here: https://github.com/blevesearch/bleve/issues/1606#issuecomment-993150219
=> [v14] Move all iterator forward until a match, only if possible

memuvarint.go
This bounds check is to return an empty uint64 while
decoding a 64-bit integer, should the reader have already
read all the bytes available.
For: https://github.com/blevesearch/bleve/issues/1651
```
Some context on the memUvarintReader ..
The code here reflects ReadUVarint(..) from
https://cs.opensource.google/go/go/+/refs/tags/go1.13.7:src/encoding/binary/varint.go
But as reported here: https://github.com/golang/go/issues/40618,
it appears it contained an error prone path that was addressed in 1.15.
```
=> Place bounds check within memUvarintReader's ReadUvarint

memuvarint.go
This bounds check is to return an empty uint64 while
decoding a 64-bit integer, should the reader have already
read all the bytes available.
For: https://github.com/blevesearch/bleve/issues/1651
```
Some context on the memUvarintReader ..
The code here reflects ReadUVarint(..) from
https://cs.opensource.google/go/go/+/refs/tags/go1.13.7:src/encoding/binary/varint.go
But as reported here: https://github.com/golang/go/issues/40618,
it appears it contained an error prone path that was addressed in 1.15.
```
=> [v11] Place bounds check within memUvarintReader's ReadUvarint

memuvarint.go
This bounds check is to return an empty uint64 while
decoding a 64-bit integer, should the reader have already
read all the bytes available.
For: https://github.com/blevesearch/bleve/issues/1651
```
Some context on the memUvarintReader ..
The code here reflects ReadUVarint(..) from
https://cs.opensource.google/go/go/+/refs/tags/go1.13.7:src/encoding/binary/varint.go
But as reported here: https://github.com/golang/go/issues/40618,
it appears it contained an error prone path that was addressed in 1.15.
```
=> [v14] Place bounds check within memUvarintReader's ReadUvarint

docvalues.go, go.mod, go.sum, intDecoder.go, posting.go, read.go, segment.go
=> A new stat for bytes read off the disk

contentcoder.go, docvalues.go, intDecoder.go, intcoder.go, new.go, posting.go, segment.go
The newly introduced stats in the PR [#1702](https://github.com/blevesearch/bleve/pull/1702) and [#117](https://github.com/blevesearch/zapx/pull/117)
are currently computed all time the irrespective of whether or not its needed. Since it is in a fairly hot code path, it could affect the performance when these stats are not needed. Hence, this PR aims to hide those stats computation behind a flag which controls the same.
=> Fix IO Stats computation

contentcoder.go, docvalues.go, intDecoder.go, intcoder.go, new.go, posting.go, segment.go
It looks like the IO stats computation is causing too much of a performance overhead in terms of query throughput and latency. Making the stats computation optional until further optimisations are pushed in.
=> Making IO Stats Optional

posting.go, segment.go
This a backward compatibility PR in reference to https://github.com/blevesearch/scorch_segment_api/pull/20
=> Update zap v11.x with the DiskStatsReporter changes

posting.go, segment.go
This is a backward compatibility PR in references to changes in https://github.com/blevesearch/scorch_segment_api/pull/20
=> Updating zap v12.x with DiskStatsReporter changes

posting.go, segment.go
This is a backward compatibility PR in references to changes in https://github.com/blevesearch/scorch_segment_api/pull/20
=> Update zap v13.x with DiskStatsReporter changes

contentcoder.go, docvalues.go, intDecoder.go, intcoder.go, new.go, posting.go, segment.go
Reverts blevesearch/zapx#131
- These changes are not necessary since the optimisation solves the regression issue https://github.com/blevesearch/bleve/issues/1731
=> Revert "Making IO Stats Optional"

contentcoder.go
An unaligned atomic bug was unfortunately introduced in #119 because the `bytesWritten` field was placed at the end of the `chunkedContentCoder` struct.
This places this after the bytes.Buffers and the bool causing it to be misaligned.
The ideal placement of this variable is not entirely clear but placing it before the progresiveWrite bool should help.
An alternative would be to just place this atomic field at the top of the struct then there would be no risk of it becoming misaligned in future.
I moved a few things around to reduce the size of the struct too but it could be possible to adjust things a little more to make the struct a little smaller.
Signed-off-by: Andrew Thornton <art27@cantab.net>
=> Fix alignment in chunkedContentCoder

contentcoder.go
Following the fix in #147, a 'panic: unaligned 64-bit atomic operation' is still occurring on some platforms.
As noted in #147, this commit implements the alternative fix by placing the bytesWritten field at the top of the struct. Per the Golang [sync/atomic documentation](https://pkg.go.dev/sync/atomic#pkg-note-BUG), on ARM, 386 and 32-bit MIPS systems, this is the reliable way to prevent these issues.
=> Fixed 64-bit alignment panic in chunkedContentCoder on 32-bit platforms.

posting.go
Possibly related to: https://github.com/blevesearch/bleve/issues/1811
=> Update PostingsList's chunkSize only when err == nil

merge.go
If there isn't an entry for a field within fieldsMap, fieldID
is set to -1 causing the following array lookup to panic ..
```
panic: runtime error: index out of range [-1]
goroutine 205 [running]:
github.com/blevesearch/zapx/v15.mergeStoredAndRemap.func2(0xc0076e2cf0, 0x27, 0x74, 0xc005d7cd3c, 0x15, 0x336b8, 0x0, 0x0, 0x0, 0x1)
/builds/gopath/pkg/mod/github.com/blevesearch/zapx/v15@v15.2.1/merge.go:722 +0x57b
github.com/blevesearch/zapx/v15.(*SegmentBase).visitStoredFields(0xc000770800, 0xc001c14000, 0x5d7, 0xc002777698, 0x2df, 0x0)
/builds/gopath/pkg/mod/github.com/blevesearch/zapx/v15@v15.2.1/segment.go:382 +0x39c
```
Ref: https://github.com/blevesearch/bleve/issues/1648
=> Check if field exists within segment's visitStoredFields callback

posting.go, segment.go
- Handling this case will help in avoiding any downstream empty slice panics that might occur.
- An example with respect to this panic is as follows:
```
panic: runtime error: index out of range [0] with length 0   
goroutine 1537342 [running]: github.com/blevesearch/vellum.(*fstStateV1).isEncodedSingle(...) 
/home/couchbase/.cbdepscache/gomodcache/pkg/mod/github.com/blevesearch/vellum@v1.0.8/decoder_v1.go:100 github.com/blevesearch/vellum.(*fstStateV1).TransitionFor(0xc014e04de0?, 0x40?) 
/home/couchbase/.cbdepscache/gomodcache/pkg/mod/github.com/blevesearch/vellum@v1.0.8/decoder_v1.go:239 +0x2d2 github.com/blevesearch/vellum.(*FST).get(0xc014e11cc0, {0xc01c7db558, 0x5, 0xc010531a68?}, {0x15cac98, 0xc01cb846e8}) 
/home/couchbase/.cbdepscache/gomodcache/pkg/mod/github.com/blevesearch/vellu …
```
=> Error handling for empty vellum data

faiss_vector_posting.go, go.mod, go.sum, section_faiss_vector_index.go
- freeing up memory held by the vector indexes once they are no longer used.
=> memory leak fixes

faiss_vector_posting.go, section_faiss_vector_index.go
- there are intermittent errors occuring while reading an index/reconstructing the vectors from it using a key. 
`Error in Index *faiss::read_index(IOReader *, int) at /Users/thejasbhat/fts/vector_search/faiss/faiss/impl/index_read.cpp:1028: Index type 0x00000000 ("\x00\x00\x00\x00") not recognized`
`Error in virtual void faiss::Index::reconstruct_batch(idx_t, const idx_t *, float *) const at /Users/thejasbhat/fts/vector_search/faiss/faiss/Index.cpp:70: Error in virtual void faiss::IndexIDMap2Template<faiss::Index>::reconstruct(idx_t, typename IndexT::component_t *) const [IndexT = faiss::Index] at /Users/thejasbhat/fts/vector_search/faiss/faiss/IndexIDMap.cpp:236: key 7274484443284373504 not found`
- refactoring the index.Close() calls so that the memory cleanup is more responsible.
- …
=> bug fix: reconstruct failing due to key not found

go.mod, go.sum
* e5f7515 Thejas-bhat | bug fix: copying the serialized content from C heap to go (#8)
=> MB-59569: Upgrade to blevesearch/go-faiss@v1.0.3

faiss_vector_posting.go, section_faiss_vector_index.go
- the aim of the PR is to avoid storing a bitmap when the vector is present in a single document. this helps to avoid building the bitmap from a buffer and just do a cheaper decoding the uint value from the bytes on the index file.
=> optimization: avoiding storing of bitmaps when vector is in a single document

cmd/zap/cmd/vector.go, faiss_vector_posting.go, faiss_vector_test.go, section_faiss_vector_index.go
- when there is a doc update, there could be a case where the number of valid docs for a vector (after remapping to the new docIDs) is zero. in this case, we shouldn't account the vector to be included in reconstruction and also should be considered as something invalid (deleted) so that we can remove that vector from the index.
- fixing the decoding of segment data in `vector` cmd tool.
- fixing the vector code formation on the postings list. essentially the score can be negative in case of dot product, however due to the right shift being 31 earlier we were reading the sign bit to be the part of docNum as well which caused incorrect doc nums to be returned. the fix for this is to shift the bits by right the number = 32.
=> bug fix: fixing the logic of tracking vector ids during a merge

section_faiss_vector_index.go, section_inverted_text_index.go
- using the specific error (seg.ErrClosed) is necessary to gracefully exit the ongoing merge operation at the scorch side.
- also contains changes with respect to using atomics for the IO stats computation for the unit test fixes.
=> MB-60071 - using the appropriate error value when the closeCh is closed

faiss_vector_test.go, section_faiss_vector_index.go
Consider the following case:
A segment with an existing IVF index has a large number of deleted vectors due to mutations, etc. Post merge, due to the lesser number of vectors, a flat index will be created. In the current approach, we were attempting to remove vector IDs from an IVF index with a hashtable using a batch ID selector which isn't supported. Hence, the panic seen in the ticket.
This PR adopts an approach where mergeFrom() is applied only if the existing indexes are all flat and the new index to be formed is flat too.
In the process, I've also made some minor changes:
1.  limited training to only IVF indexes - flat indexes don't need to be trained.
2. done a minor refactoring of the utilities used by related UTs.
=> MB-60084: Change index merge procedure to account for existing index type.

section_faiss_vector_index.go
- The `mergeAndWriteVectorIndexes() ` is called whenever we are trying to merge multiple vector indexes. As part of that we are tracking the participating vector indexes' metadata as part of `vecIndexMeta` - which has the ids corresponding to the set of valid vectors and also the ids of those vectors that have been deleted/are obsolete. 
- Earlier, we were passing all the segments to the func and merging the valid vector indexes. However, that caused issues with respect to accessing nil/empty values. 
- The PR corrects this by passing only the segments having the valid vector content in it.
=> MB-60152: Panic fix while trying to fetch metadata of a vector index

faiss_vector_posting.go, faiss_vector_test.go
- drops the unnecessary masking bits while fetching the score since uint32() type cast does the same thing.
- the zapx and bleve unit tests (with the vectors tag) pass so i don't see any regression from the search result wise for the vector search tests.
```
zapx 
➜ go test ./... --tags=vectors
ld: warning: dylib (/usr/local/lib/libfaiss_c.dylib) was built for newer macOS version (11.7) than being linked (11.0)
?   	github.com/blevesearch/zapx/v16/cmd/zap	[no test files]
?   	github.com/blevesearch/zapx/v16/cmd/zap/cmd	[no test files]
ok  	github.com/blevesearch/zapx/v16	4.508s
bleve
➜ go test ./... --tags=vectors
ld: warning: dylib (/usr/local/lib/libfaiss_c.dylib) was built for newer macOS version (11.7) than being linked (11.0)
? …
```
=> TestVecPostingsIterator unit test fix

section_faiss_vector_index.go
This PR addresses 2 merge path issues - 
A. IDs need to be added to a vector index in the _same order as the vectors_ to maintain the integrity of the mapping between vectors and IDs which is important for both search and reconstruction. 
When reconstructing indexes, the current approach uses the keys of a map to decide the order of the final vector IDs. However, since the Keys() function provides no guarantee of ordering of the returned list, the vectors and IDs are not guaranteed to be inserted in the same order.
B. Currently, merging flat indexes involves adding all existing flat indexes into an existing index. 
1. This indexes duplicate vectors - since a hash is unique to a vector, 2 segments with the same vectors in an index will have the same hash. merge_from() adds duplicate …
=> MB-60269 - Merge path fixes

cmd/zap/cmd/vector.go, faiss_vector_posting.go, faiss_vector_test.go, go.mod, go.sum, section_faiss_vector_index.go
This PR addresses filtering of deleted documents by moving from post-filtering to search time filtering. 
- Passes doc IDs to exclude for each search.
- To account for duplicate vectors: saves every vector with a unique hash so that the selector only excludes the specific vector ID. The current approach of identical vectors having identical hashes would lead to (unnecessarily) excluding vectors if other (identical) vectors in the segment were deleted.
=> MB-60202 - Filtering deleted documents during FAISS vector index search

build.go, dict.go, go.mod, go.sum, merge.go, section_faiss_vector_index.go, section_inverted_text_index.go, segment.go, write.go
All the points below remove garbage to some extent
- Implement caching for MaxDocID in a segment, leveraging the immutability of the FST for the segment. This enhancement is particularly beneficial for the Introducer Loop, where the DocNumbers() API is called for each segment in the root. By storing the MaxDocID and avoiding redundant recomputation using fst.GetMaxKey(). We also cache the ID Dict for a segment to avoid generating the same object multiple times, saving on the space alloced to repeated creations of the FST Reader object.
- Optimize the writeVectorIndexes function by preventing repeated append scenarios. This is achieved by preallocating the necessary memory through an additional for loop, enhancing efficiency.
- Close the enumerator, to free the FST iterators
- Add …
=> MB-60400: Reduce Garbage generated

cmd/zap/cmd/vector.go, faiss_vector_posting.go, faiss_vector_test.go, section_faiss_vector_index.go
- Restructuring the code around merge path to help free the memory occupied by the vecToDocID better. 
- Using pointers to struct to avoid copying of values while ranging over the map during the introduction phase of code
- Tests performed on these were: 
- Indexing 1M sift dataset vector content - merge paths are getting hit - no crashes etc. 
- Querying on the built index - no crashes/faults observed over there 
- Point mutations leading to merge segments without vector content with a vector content along with querying on this index to see the results - showing results as per expectations 
- cmd tool parses the index file find 
- force one last time to perform the same query - results as per expectation
=> MB-60367 Restructuring the code for better memory cleanup

faiss_vector_posting.go, go.mod, go.sum
- Added an UpdateFieldStats function which will populate the passed map with any field related metrics
- The map is expected to be already initialized with the appropriate metric names
- As of now, the only metric added is num_vectors which is obtained by looking at its appropriate field section data
- This call also is only necessary after a merge because otherwise we can obtain it from the analysis results.
- With the inclusion of UpdateFieldStats, SegmentBase will now implement the FieldStatsReporter defined in scorch_segment_api
=> MB-60914: Zap field specific metrics

build.go, faiss_vector_cache.go, faiss_vector_cache_noop.go, faiss_vector_cache_nosup.go, faiss_vector_posting.go, segment.go
- Uses the exponentially weighted moving average to get the average hits on a particular field (thereby a particular vector index). The index stays in the memory when the average of the hits is above a certain threshold and below which the index is closed and the memory is freed for reuse on C side of things.
- This ensures that we are not keeping the index in the memory even when there is no query workload on the field in a segment so the memory pressure does get reduced on the C side of operations.
=> MB-61029: Deferring the closing of vector index

faiss_vector_test.go, section_faiss_vector_index.go
- Ensure slice capacities are accurately calculated to always be equal to the final slice length
- Fix test to cleanup zap segment after completion
=> minor optimizations and bug fixes

faiss_vector_cache.go, faiss_vector_posting.go
- Generalized some of the cache functions
- Cache will include vec to docid mapping as well as one structure to help vec excluded calculation as well as the vec excluded structure
- Added back the cache mutexes because cache reads will also write back some of the structures depending on the except bitmap
=> MB-61029: Caching Vec To DocID Map

go.mod, go.sum
To include:
* 693b06a Rahul Rampure | MB-61650: Release IDSelectorBatch's batchSelector to avoid memory leak
=> MB-61650: Upgrade blevesearch/go-faiss

go.mod, go.sum
Includes:
* d8f2ddf Abhi Dangeti | MB-60697: Windows requires nprobe to be of 'long long' type (#24)
* 9bb55f8 Abhi Dangeti | Retain IDSelector's Delete() API for complete-ness
=> MB-60697: Upgrade blevesearch/go-faiss for windows fix

section_faiss_vector_index.go
This PR reduces the number of centroids for vectors in sizes ranging from 200k to 1M. Since the reduction in training time is linearly dependent on reduction in centroids, this is to drive down training time.
=> MB-60943 - Reduce number of centroids for IVF indexes.

faiss_vector_cache.go, faiss_vector_io_flags_unix.go, faiss_vector_io_flags_win.go, section_faiss_vector_index.go
- Faiss does not support OnDiskInvertedLists on windows, and hence while using go-faiss's IO flags, we must take into account the build platform.
- This PR enforces the old faiss.IOFlagReadOnly flag for windows and maintains the existing io flags for unix based platforms.
=> MB-62167: Fix windows crash

go.mod, go.sum, section_faiss_vector_index.go
- Set FAISS vector metric to be `MetricInnerProduct`, if the distance metric from bleve is either `Cosine` or `InnerProduct`
=> MB-62354: Support Cosine Similarity

faiss_vector_test.go
```
./faiss_vector_test.go:489:59: not enough arguments in call to vecSeg.InterpretVectorIndex
have (string, nil)
want (string, bool, *roaring.Bitmap)
./faiss_vector_test.go:583:59: not enough arguments in call to vecSeg.InterpretVectorIndex
have (string, nil)
want (string, bool, *roaring.Bitmap)
```
=> Fix unit test breakage from previous commit (API change)

go.mod, go.sum
This selector fix is essential to reduce the number of centroids to consider to determine those closest.
Brings in:
* b64c588 Aditi Ahuja | MB-62230 - Use a selector to pick centroid IDs
=> MB-62230: Upgrade blevesearch/go-faiss for selector fix

build.go, faiss_vector_cache.go, merge.go, new.go, segment.go, write.go
- Fix issue where `vecIDsToExclude` is always nil if the cache entry exists, allowing deleted documents to be returned.
- Optimize vector cache logic by checking for a cache entry after acquiring a write lock to reduce redundant work during concurrent access.
- Resolve issue of duplicate entries being added to `dictLocs` when constructing an in-memory segment.
- Clean up code by removing the unused method parameters that were being passed around.
=> Bug fixes and Optimizations

chunk.go, posting.go
The existing implementation of the method
getChunkSize(...) (uint64, error), in some cases,
can return chunkSize==0 and err==nil.
The onus is on the caller to check for such possibility and handle it properly.
Callers often use the returned chunkSize as a divisor and a zero chunkSize lead to panic.
see https://github.com/blevesearch/zapx/issues/209
This PR intends to update the method implementation to always return an error in case the returned chunkSize value is 0.
That way caller need to only worry about error being non-nil.
Callers which are ok with 0 chunkSize can check the returned error against ErrChunkSizeZero
=> Handle zero chunk size

chunk.go
Extends on https://github.com/blevesearch/zapx/pull/263
=> One more case for zero chunk size / mode

faiss_vector_posting.go, go.mod, go.sum
1. Add elements to the bitmap in a batch instead of individually to bring down latencies of pre-filtered queries.
2. Vary the selector used and use an exclude selector with high selectivity.
=> MB-62230 - Pre-filtering performance optimisations

contentcoder.go, docvalues.go, intDecoder.go, intcoder.go, new.go
- the construct of bytes written while constructing a segment is not a shared resource i.e. a single thread operates on a segment creation. Hence the atomic.Add() operation is not necessary here.
- Tested using bleve unit test with race flace 
```
go test -run=TestBytesWritten --race
PASS
ok  	github.com/blevesearch/bleve/v2	2.294s
```
=> MB-57871 - [v15] Avoid unnecessary atomic operation on bytesWritten

contentcoder.go, docvalues.go, intDecoder.go, intcoder.go, section_inverted_text_index.go
- the construct of bytes written while constructing a segment is not a shared resource i.e. a single thread operates on a segment creation. Hence the atomic.Add() operation is not necessary here.
- Tested using bleve unit test with race flace 
```
go test -run=TestBytesWritten --race
PASS
ok  	github.com/blevesearch/bleve/v2	2.294s
```
=> MB-57871 - Avoid unnecessary atomic operation on bytesWritten

faiss_vector_posting.go
Use AddMany() when populating cluster assignment map with vectors belonging to a cluster.
=> MB-62230 - More pre-filtering optimisations

section_faiss_vector_index.go
- In update/delete heavy scenario where we short circuit the merge path, we end up reading a faiss index to the memory unnecessarily and it can potentially stay in memory till the reconstruction of all valid vectors is complete (which is not ideal).
- Also refactoring the `vecIndexes []*faiss.IndexImpl` construct to `indexes []*vecIndexInfo` just so we don't have to read info from two different slices while reconstructing vectors.
=> Handling a case to avoid bringing faiss index to memory unnecessarily

section_inverted_text_index.go, segment.go
It's the same story as per #148, but for v16.
```
panic: unaligned 64-bit atomic operation
goroutine 1 [running]:
internal/runtime/atomic.panicUnaligned()
/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-386/src/internal/runtime/atomic/unaligned.go:8 +0x2d
internal/runtime/atomic.Xadd64(0xa0226e4, 0x0)
/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-386/src/internal/runtime/atomic/atomic_386.s:125 +0x11
github.com/blevesearch/zapx/v16.(*invertedIndexOpaque).incrementBytesWritten(...)
/root/go/pkg/mod/github.com/blevesearch/zapx/v16@v16.1.5/section_inverted_text_index.go:401
github.com/blevesearch/zapx/v16.(*invertedIndexOpaque).writeDicts(0xa022608, 0xfd7efa8)
/root/go/pkg/mod/github.com/blevesearch/zapx/v16@v16.1.5/section_inverted_text_index.go:529 +0xe74 …
```
=> Fixed 64-bit alignment panic on 32-bit platforms

faiss_vector_posting.go
Return early when applicable and avoid unnecessary nesting of code.
=> [faiss_vector_posting] Refactor searchWithFilter for readability

faiss_vector_cache.go, faiss_vector_posting.go, go.mod, go.sum
- Refactor pre-filtered vector search to enhance performance and reduce memory footprint.
- Replace the current bitmap-based cluster selection mechanism with a simpler approach that uses the DirectMap in the IVF index. The IVF index's DirectMap directly maps the vector ID to the cluster it belongs to.
- Make `github.com/bits-and-blooms/bitset` a direct dependency of `zapx` and upgrade it to
the latest version
- Requires https://github.com/blevesearch/go-faiss/pull/41
---------
=> MB-65473: [BP] Refactor and Optimize Pre-Filtered Vector Search (#317)
